deps = [
    '//:commons-cli',
    '//:commons-compress',
    '//:commons-lang3',
    '//:commons-text',
    '//:dictzip',
    '//:emoji-java',
    '//:jackson-annotations',
    '//:jackson-core',
    '//:jackson-databind',
    '//:jackson-dataformat-yaml',
    '//:json',
    '//:snakeyaml'
]

java_library(
    name="main-lib",
    srcs=glob(["**/*.java"]),
    deps=deps,
    visibility=['PUBLIC']
)